Compute sdk
spheronFdn/sdk pull request #104
Opened 2023-04-24 09:14 UTC by ilij4

2023-04-24 09:18 UTC, shomix commented on packages/compute/package.json
> +  "version": "0.0.1",
use `1.0.0` for version

2023-04-24 09:18 UTC, shomix commented on packages/compute/package.json
> +    "IPFS",
revmove ipfs

2023-04-24 09:18 UTC, shomix commented on packages/compute/package.json
> +    "@spheron/core": "^1.0.1"
need to. increase the version of `core`

2023-05-06 07:14 UTC, rekpero requested changes
some review comments regarding renaming and all, otherwise lgtm, we can release this next week monday

2023-05-06 07:14 UTC, rekpero commented on packages/core/src/spheron-api/request-interfaces.ts
> +interface ClusterDeploymentVariable {
```suggestion
interface DeploymentVariable {
```

2023-05-06 07:14 UTC, rekpero commented on packages/core/src/spheron-api/interfaces.ts
> +  _id: string;
```suggestion
  id: string;
```

2023-05-06 07:14 UTC, rekpero commented on packages/core/src/spheron-api/interfaces.ts
> +  _id: string;
```suggestion
  id: string;
```

2023-05-06 07:14 UTC, rekpero commented on packages/core/src/spheron-api/interfaces.ts
> +  _id: string;
```suggestion
  id: string;
```

2023-05-08 13:59 UTC, ilij4 commented on packages/core/src/spheron-api/interfaces.ts
> +  _id: string;
We will be exporting types from compute sdk interfaces file, all the renaming and removing of fields is done there

2023-05-09 17:40 UTC, rekpero requested changes
last couple of comments buddy

2023-05-09 17:40 UTC, rekpero commented on packages/compute/README.md
> +await computeClient.clusterInstance.create(
update this snippet @ilij4

2023-05-09 18:34 UTC, ilij4 commented on packages/core/src/spheron-api/index.ts
> +      console.log("----------------- RESPONSE ------------------");
leftover from testing, removing it...

2023-05-10 08:27 UTC, shomix commented on packages/core/src/spheron-api/index.ts
> +  private readonly spheronApiUrl: string = "https://api-dev.spheron.network";
Dont forget to revert this

2023-05-10 08:27 UTC, shomix commented on packages/core/src/spheron-api/index.ts
> +    return this.sendApiRequest<InstanceResponse>(
add await after return. There is a difference if the function returns a awaited promise and a promise.

https://stackoverflow.com/questions/38708550/difference-between-return-await-promise-and-return-promise

Do it for all functions.

2023-05-10 08:27 UTC, shomix commented on packages/compute/tsconfig.json
> +  "include": ["./src/**/*", "../core/src/cluster-manager.ts"],
what is this path that goes outside the directory of the project?
`..code/src/cluster-manager.ts`?

2023-05-10 10:14 UTC, ilij4 commented on packages/core/src/spheron-api/index.ts
> +    return this.sendApiRequest<InstanceResponse>(
error handling wont work only in case return itself is wrapped in try/catch. In our case user will have await and try catch around it so there is no need for adding return await

2023-05-12 06:55 UTC, rekpero requested changes
some more RC for you @ilij4

2023-05-12 06:55 UTC, rekpero commented on packages/compute/README.md
> +      akashMachineImageName: machineType,
please check this @ilij4

2023-05-12 06:55 UTC, rekpero commented on packages/compute/README.md
> +To create the `token` that is used with the `SpheronComputeClient`, follow the instructions in the [DOCS](https://docs.spheron.network/rest-api/#creating-an-access-token). When you are creating the t
```suggestion
To create the `token` that is used with the `SpheronComputeClient`, follow the instructions in the [DOCS](https://docs.spheron.network/rest-api/#creating-an-access-token). When you are creating the tokens, please choose **compute** type in the dashboard.
```

2023-05-12 06:55 UTC, rekpero commented on packages/compute/README.md
> +You can learn more about Spheron and Storage SDK here:
```suggestion
You can learn more about Spheron and Compute SDK here:
```

2023-05-12 06:55 UTC, rekpero commented on packages/compute/README.md
> +For more information about the Site methods, check out the [DOCS](https://docs.spheron.network/sdk/compute/)
```suggestion
For more information about the Compute methods, check out the [DOCS](https://docs.spheron.network/sdk/compute/)
```

2023-05-12 06:55 UTC, rekpero commented on packages/compute/README.md
> +      command: [],
```suggestion
      commands: [],
```
should be commands

2023-05-12 06:55 UTC, rekpero commented on packages/compute/README.md
> +    healthCheckUrl: healthCheckPath,
is this needed? cause I don't think everyone need to pass this always. make this optional or 
```
healthCheckConfig?: {
 url: "some",
 port: "9090"
}
```
This `healthCheckConfig` can be optional, wdyt? @ilij4

2023-05-12 06:55 UTC, rekpero commented on packages/compute/src/index.ts
> +export class SpheronComputeClient {
```suggestion
export class SpheronClient {
```

2023-05-15 11:41 UTC, ilij4 commented on packages/compute/README.md
> +    healthCheckUrl: healthCheckPath,
@rekpero it is optional, just didnt put it here as ?: since its example of usage

2023-05-15 11:43 UTC, ilij4 commented on packages/compute/README.md
> +    healthCheckUrl: healthCheckPath,
@rekpero yes, it is optional, will wrap it up in that config tho

2023-05-15 15:31 UTC, rekpero requested changes
check my RC @ilij4

2023-05-15 15:31 UTC, rekpero commented on packages/compute/src/mappers.ts
> +      bandwidth: usage.bandwidthLimit,
```
clusterAktLimit?: number; -> rename this to computeCreditLimit: number,  add used compute credit 
clusterBuildExecutionLimit?: number; -> cluster to compute, add used build execution too
domainsLimit: number; -> add usedDomain too
usedNumberOfRequests: number
```

2023-05-15 15:31 UTC, rekpero commented on packages/compute/src/interfaces.ts
> +    instanceCount: number;
make it `scale`

2023-05-15 15:31 UTC, rekpero commented on packages/compute/src/interfaces.ts
> +    instanceCount: number;
make it scale

2023-05-15 15:53 UTC, rekpero commented on packages/compute/src/interfaces.ts
> +  machineImageId: string;
it's fine for now, we can take this in the version

2023-05-23 08:56 UTC, dusanstanis commented on packages/compute/src/index.ts
> +export class SpheronClient {
this is cool

2023-05-23 08:56 UTC, dusanstanis submitted a review, later dismissed
Looks really cool, gj !

2023-05-23 10:37 UTC, shomix approved these changes

2023-05-23 12:34 UTC, Man-Jain approved these changes

2023-05-25 06:25 UTC, rekpero approved these changes
lgtm

2023-05-25 13:49 UTC, rekpero approved these changes

2023-05-25 14:20 UTC, dusanstanis approved these changes

2023-05-25 14:26 UTC, shomix approved these changes

2023-05-25 14:32 UTC, merged