Add method to return CDN domain values
spheronFdn/sdk pull request #126
Opened 2023-06-13 18:28 UTC by shomix

This PR will:
- Add a new method `getCdnValues` to the `storage` sdk. This method will return values which need to be added to the domain record so that it can be verified. 
  - `cdnDomainValue` - will contain the value that should be added for domains
  - `cdnSubdomainValue` - will contain the value that should be added for subdomain.
---
After approval.
- [ ] Add method to the docs and Readme.
- [ ] Check to see if we want to add the method to other packages.

2023-06-15 11:06 UTC, rekpero requested changes
check my comments

2023-06-15 11:06 UTC, rekpero commented on packages/storage/src/index.ts
> +  async getCdnValues(): Promise<{
```suggestion
  async getCdnDnsRecords(): Promise<{
```

2023-06-15 11:06 UTC, rekpero commented on packages/storage/src/index.ts
> +      cdnDomainValue: recordIpv4V2,
```suggestion
      cdnARecords: recordIpv4V2,
```

2023-06-15 11:06 UTC, rekpero commented on packages/storage/src/index.ts
> +      cdnSubdomainValue: recordCnameV2,
```suggestion
      cdnCnameRecords: recordCnameV2,
```

2023-06-15 12:51 UTC, shomix commented on packages/storage/src/index.ts
> +  async getCdnValues(): Promise<{
Updated

2023-06-15 12:51 UTC, shomix commented on packages/storage/src/index.ts
> +      cdnDomainValue: recordIpv4V2,
Updated.

2023-06-15 12:52 UTC, shomix commented
@rekpero added the `getCdnDnsRecords` to site and compute as well.

2023-06-15 12:53 UTC, rekpero submitted a review, later dismissed

2023-06-16 16:22 UTC, dusanstanis commented on packages/site/package.json
> +    "@spheron/core": "1.0.7",
1.0.8 here ? Yesterday we released 1.0.7

2023-06-16 16:25 UTC, shomix commented on packages/compute/package.json
> +    "@spheron/core": "^1.0.7"
yep, fixed.

2023-06-16 16:25 UTC, shomix commented on packages/site/package.json
> +    "@spheron/core": "1.0.7",
yep, fixed.

2023-06-16 16:26 UTC, rekpero approved these changes

2023-06-19 09:52 UTC, rekpero approved these changes

2023-06-19 10:20 UTC, dusanstanis approved these changes

2023-06-19 10:24 UTC, merged