Add manual scaling to SDK
spheronFdn/sdk pull request #144
Opened 2023-08-28 15:57 UTC by L-tech

2023-08-29 09:42 UTC, ilij4 commented on packages/compute/src/interfaces.ts
> +    akashMachineImageName?: string;
we already have machineImageId property in this config. There is no need to add this as well

2023-09-05 09:30 UTC, dusanstanis submitted a review, later dismissed

2023-09-05 09:37 UTC, ilij4 submitted a review, later dismissed

2023-09-12 16:24 UTC, rekpero requested changes
make a check if the compute type is spot or on-demand, if spot throw error saying can't update these specs

2023-09-15 16:14 UTC, rekpero approved these changes

2023-09-18 14:18 UTC, dusanstanis commented on packages/compute/README.md
> +    type: ComputeTypeEnum.DEMAND,
Just check if u map this later to send it as :
scaling: true 
or 
scaling: false 

Cuz api supports only that. But it's fine to have it like this on your side, just make sure to map it properly @L-tech

2023-09-18 15:40 UTC, L-tech commented on packages/compute/README.md
> +    type: ComputeTypeEnum.DEMAND,
Yes. There is a mapping for it - https://github.com/spheronFdn/sdk/blob/96bcdf51d63e9c6dc1d38756970bd234fc712f4d/packages/compute/src/mappers.ts#L285 
@dusanstanis

2023-09-18 16:43 UTC, merged