Add support of lit sdk v3
spheronFdn/sdk pull request #174
Opened 2024-02-21 06:27 UTC by aayushmahapatra

2024-03-06 03:41 UTC, rekpero requested changes
lgtm, need small changes but did you test if it's working properly or not also share a live demo (small video recording on the usecase)

2024-03-06 03:41 UTC, rekpero commented on examples/storage-encryption/src/encrypt.js
> +const chain = "mumbai";
why did we change this to polygon testnet? this shouldn't be changed or add it as a param for others to pass their required chain

2024-03-06 03:41 UTC, rekpero commented on packages/storage/src/index.ts
> +  }: any): Promise<any> {
why any?

2024-03-26 10:06 UTC, rekpero approved these changes

2024-04-26 16:18 UTC, ilij4 approved these changes

2024-04-26 16:20 UTC, merged