Update sdk monorepo and storage readme
spheronFdn/sdk pull request #20
Opened 2023-02-18 09:28 UTC by aayushmahapatra

2023-02-18 09:30 UTC, shomix approved these changes

2023-02-18 09:30 UTC, shomix commented on README.md
> +```js
Nice, didn't know about this.

Should we also do it for the README.md in the `packages/storage/` folder?

2023-02-18 09:44 UTC, aayushmahapatra commented on README.md
> +```js
Done 👍🏻

2023-02-18 11:01 UTC, rekpero requested changes

2023-02-18 11:01 UTC, rekpero commented on packages/storage/README.md
> +  🧰 Developer toolkits for web3 cloud infrastructure, powered by Spheron.
this should be talking about the multi-chain storage SDK
```suggestion
  🧰 SDK for multi-chain storage, powered by Spheron.
```

2023-02-19 07:09 UTC, rekpero approved these changes

2023-02-20 03:56 UTC, rekpero requested changes

2023-02-20 03:56 UTC, rekpero commented on packages/storage/README.md
> +  <img src="https://img.shields.io/static/v1?label=npm&message=v14.0.0&color=green" />
```suggestion
  <img src="https://img.shields.io/static/v1?label=npm&message=v1.0.3&color=green" />
```
This should the current npm package version not node lts

2023-02-20 05:01 UTC, rekpero commented on packages/storage/README.md
> +  <img src="https://img.shields.io/static/v1?label=npm&message=v14.0.0&color=green" />
Also this link should redirect user to npm package

2023-02-20 05:02 UTC, rekpero requested changes

2023-02-20 05:02 UTC, rekpero commented on packages/storage/README.md
> +  <img src="https://img.shields.io/static/v1?label=license&message=Apache%202.0&color=red" />
this should direct user to github license page

2023-02-20 14:52 UTC, aayushmahapatra commented on packages/storage/README.md
> +  <img src="https://img.shields.io/static/v1?label=npm&message=v14.0.0&color=green" />
Github package link or npmjs? 🤔

2023-02-21 14:08 UTC, rekpero submitted a review, later dismissed

2023-02-21 15:41 UTC, shomix approved these changes

2023-02-21 15:42 UTC, rekpero approved these changes

2023-02-21 15:44 UTC, merged