[WIP] Add methods for working with buckets
spheronFdn/sdk pull request #23
Opened 2023-02-21 22:11 UTC by shomix

2023-03-14 13:36 UTC, dusanstanis commented on packages/storage/src/bucket-manager/index.ts
> +  async getBucket(bucketId: string): Promise<Bucket> {
Why don't we call it Project ? We want to abstract it in bucket for what reason ? :D

2023-03-14 13:36 UTC, dusanstanis submitted a review, later dismissed

2023-03-15 11:17 UTC, shomix commented on packages/storage/src/bucket-manager/index.ts
> +  async getBucket(bucketId: string): Promise<Bucket> {
Yeah, in storage SDK there is a mappint:
project -> bucket
deployment -> upload

2023-03-15 13:34 UTC, shomix commented on packages/storage/src/bucket-manager/index.ts
> +  async getBucket(bucketId: string): Promise<Bucket> {
So essentially this functions are just a wrap around our REST API, and they map the models for Deployment and Project, to Upload and Bucket.
When mapping we just take the properties that are useful for the upload context.
For example, Project has env variables and deployment environments, but they are removed from the Bucket, because it cannot have it.

2023-03-16 14:18 UTC, rekpero requested changes
some comments regarding _id

2023-03-16 14:18 UTC, rekpero commented on packages/storage/README.md
> +  _id: string;
can we have this as id rather than _id
```suggestion
  id: string;
```

2023-03-16 14:18 UTC, rekpero commented on packages/storage/README.md
> +  _id: string;
same here

2023-03-16 14:21 UTC, shomix commented on packages/storage/README.md
> +  _id: string;
Updated in Readme and in real interfaces.

2023-03-16 14:21 UTC, shomix commented on packages/storage/README.md
> +  _id: string;
Updated in Readme and in real interfaces.

2023-03-16 14:21 UTC, dusanstanis approved these changes

2023-03-17 12:38 UTC, merged