Update readme and error handling
spheronFdn/sdk pull request #34
Opened 2023-02-27 16:05 UTC by shomix

2023-02-27 16:53 UTC, aayushmahapatra approved these changes
lgtm

2023-03-01 10:44 UTC, rekpero requested changes

2023-03-01 10:44 UTC, rekpero commented on packages/storage/src/upload-manager/index.ts
> +      const errorMessage = error?.response.data?.message || error?.message;
```suggestion
      const errorMessage = error?.response?.data?.message || error?.message;
```

2023-03-01 10:44 UTC, rekpero commented on README.md
> +        onChunkUploaded(uploadedSize, totalSize) {
why is this different looking than `onUploadInitiated` might confuse beginner devs

2023-03-01 10:45 UTC, shomix commented on README.md
> +        onChunkUploaded(uploadedSize, totalSize) {
Ahh, didn't notice it. Fixing it.

2023-03-01 10:52 UTC, shomix commented on README.md
> +        onChunkUploaded(uploadedSize, totalSize) {
Fixed.

2023-03-01 10:52 UTC, shomix commented on packages/storage/src/upload-manager/index.ts
> +      const errorMessage = error?.response.data?.message || error?.message;
Fixed.

2023-03-01 11:07 UTC, rekpero requested changes
some more RC

2023-03-01 11:07 UTC, rekpero commented on packages/storage/README.md
> +let currentlyUploaded = 0;
update the npm version in the readme npm badge

2023-03-01 11:07 UTC, rekpero commented on packages/storage/README.md
>  ...
remove these dots

2023-03-01 11:07 UTC, rekpero commented on packages/storage/README.md
>  ...
same here

2023-03-01 11:07 UTC, rekpero commented on README.md
>  ...
same here

2023-03-01 11:07 UTC, rekpero commented on README.md
>  ...
same here

2023-03-01 11:36 UTC, shomix commented on packages/storage/README.md
> +let currentlyUploaded = 0;
Updated to v8.0.5 ( this is the one I use ).
If some specific version is needed, please say which one

2023-03-01 11:36 UTC, shomix commented on packages/storage/README.md
>  ...
Removed

2023-03-01 11:36 UTC, shomix commented on packages/storage/README.md
>  ...
Removed

2023-03-01 11:36 UTC, shomix commented on README.md
>  ...
Removed

2023-03-01 11:37 UTC, shomix commented on README.md
>  ...
Removed

2023-03-01 11:43 UTC, rekpero requested changes

2023-03-01 11:43 UTC, rekpero commented on packages/storage/README.md
> +    <img src="https://img.shields.io/static/v1?label=npm&message=v8.0.5&color=green" />
not 8.0.5, this is the version of the storage package not node package

2023-03-01 11:46 UTC, vocoront1 commented on packages/storage/README.md
> +    <img src="https://img.shields.io/static/v1?label=npm&message=v8.0.5&color=green" />
haha :D didn't know about this. Fixed it.

2023-03-01 11:46 UTC, rekpero approved these changes

2023-03-01 11:51 UTC, rekpero approved these changes

2023-03-01 11:54 UTC, dusanstanis approved these changes
lgtm !

2023-03-01 11:56 UTC, merged