Add link to the create token docs to README
spheronFdn/sdk pull request #58
Opened 2023-03-09 08:50 UTC by shomix

2023-03-10 17:48 UTC, rekpero requested changes

2023-03-10 17:48 UTC, rekpero commented on README.md
> +- The `SpheronClient` constructor takes an object that has one property `token`. To create the `token`, you can follow the instructions in the [DOCS](https://docs.spheron.network/api/rest-api-referen
It's hard to find this api token section, it's better to create a section after the usage with title `Access Token` and then write down this content in there

2023-03-11 09:27 UTC, shomix commented on README.md
> +- The `SpheronClient` constructor takes an object that has one property `token`. To create the `token`, you can follow the instructions in the [DOCS](https://docs.spheron.network/api/rest-api-referen
Something like this? https://github.com/spheronFdn/sdk/blob/add-token-description-to-readme/packages/storage/README.md
![image](https://user-images.githubusercontent.com/100691266/224476479-b1cb4f42-3ae2-4178-b2fd-11bc608188c2.png)

2023-03-13 05:22 UTC, rekpero commented on README.md
> +- The `SpheronClient` constructor takes an object that has one property `token`. To create the `token`, you can follow the instructions in the [DOCS](https://docs.spheron.network/api/rest-api-referen
yes

2023-03-13 10:02 UTC, shomix commented on README.md
> +- The `SpheronClient` constructor takes an object that has one property `token`. To create the `token`, you can follow the instructions in the [DOCS](https://docs.spheron.network/api/rest-api-referen
Removed :

2023-03-13 10:03 UTC, rekpero submitted a review, later dismissed

2023-03-13 10:05 UTC, dusanstanis submitted a review, later dismissed

2023-03-13 10:05 UTC, aayushmahapatra approved these changes
LGTM

2023-03-13 10:17 UTC, aayushmahapatra approved these changes

2023-03-13 10:27 UTC, dusanstanis approved these changes

2023-03-13 10:43 UTC, merged