Add function to get the subscription usage of the organization
spheronFdn/sdk pull request #74
Opened 2023-03-15 13:27 UTC by shomix

2023-03-15 13:29 UTC, dusanstanis approved these changes

2023-04-03 11:30 UTC, shomix commented on packages/storage/src/spheron-api/interfaces.ts
> +  usedStorageSkynet?: number; // Bytes
@rekpero should we remove the usedStorageSkynet from the interface?

2023-04-03 11:35 UTC, rekpero submitted a review, later dismissed

2023-04-03 11:35 UTC, rekpero commented on packages/storage/src/spheron-api/interfaces.ts
> +  usedStorageSkynet?: number; // Bytes
yes, we should

2023-04-03 11:51 UTC, shomix commented on packages/storage/src/spheron-api/interfaces.ts
> +  usedStorageSkynet?: number; // Bytes
Removed.

2023-04-03 11:59 UTC, rekpero submitted a review, later dismissed

2023-04-03 12:03 UTC, dusanstanis submitted a review, later dismissed

2023-04-03 12:24 UTC, dusanstanis approved these changes

2023-04-03 12:25 UTC, rekpero requested changes

2023-04-03 12:25 UTC, rekpero commented on packages/storage/src/spheron-api/interfaces.ts
> +export interface UsageWithLimitsWithSkynet extends UsageWithLimits {
why is this interface required?

2023-04-03 12:29 UTC, shomix commented on packages/storage/src/spheron-api/interfaces.ts
> +export interface UsageWithLimitsWithSkynet extends UsageWithLimits {
This is what the API is returning

2023-04-03 12:31 UTC, shomix commented on packages/storage/src/spheron-api/interfaces.ts
> +export interface UsageWithLimitsWithSkynet extends UsageWithLimits {
But we are removing this properties in the `SpheronClinet` object, and just returning the `UsageWithLimits` interface.

2023-04-03 12:32 UTC, rekpero approved these changes

2023-04-03 12:35 UTC, merged