add methods to convert CID versions
spheronFdn/sdk pull request #93
Opened 2023-04-05 13:26 UTC by shomix

Linear: https://linear.app/spheron/issue/SPH-1565/add-support-for-converting-ipfs-hash-from-v0-to-v1-and-vice-versa

- added methods to convert CID V0 to V1 and vice verse.

2023-04-05 13:27 UTC, dusanstanis submitted a review, later dismissed

2023-04-05 14:30 UTC, rekpero requested changes

2023-04-05 14:30 UTC, rekpero commented on packages/storage/src/index.ts
> +  toV0,
These should be exposed like this - `ipfs.utils.toV0()`

2023-04-06 11:26 UTC, shomix commented on packages/storage/src/index.ts
> +  toV0,
Update the structure of object, the methods would be used like:

```
import { ipfs } from "@spheron/storage";

const cid = "QmYXQrCnkhQ1Jp1tU1KjFV2kEz1qRzvRkqXv3oX5r8rj1i";

console.log("CID: ", cid);

const v1 = ipfs.utils.toV1(cid);
console.log(v1);

```

2023-04-11 16:52 UTC, rekpero commented on packages/storage/src/index.ts
> +  toV0,
yup this usage looks good to me, let's merge this in the upcoming release

2023-04-11 16:52 UTC, rekpero submitted a review, later dismissed

2023-04-12 09:34 UTC, dusanstanis approved these changes

2023-04-12 10:15 UTC, Man-Jain approved these changes

2023-04-12 10:17 UTC, merged