Browser Upload Package
spheronFdn/sdk pull request #96
Opened 2023-04-07 11:56 UTC by shomix

2023-04-10 12:21 UTC, dusanstanis approved these changes

2023-04-12 16:56 UTC, rekpero requested changes
please check my comment

2023-04-12 16:56 UTC, rekpero commented on packages/browser-upload/README.md
> +const uploadResult = await upload(<FILES_YOU_WANT_TO_UPLOAD>, token);
The 2nd param looks different than the example, shouldn't this be `{ token }`

2023-04-12 17:16 UTC, shomix commented on packages/browser-upload/README.md
> +const uploadResult = await upload(<FILES_YOU_WANT_TO_UPLOAD>, token);
nice catch, fixed it.

2023-04-13 10:31 UTC, aayushmahapatra approved these changes

2023-04-13 11:03 UTC, merged